"""add_deleted_at_to_exchange_rates

Revision ID: 62cdf51dca49
Revises: db0d114b5777
Create Date: 2026-05-25 20:29:17.406675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '62cdf51dca49'
down_revision: Union[str, None] = 'db0d114b5777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_rates', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_rates', 'deleted_at')
    # ### end Alembic commands ###
