"""partial_unique_exchange_rates_currency_date

Revision ID: b46762debd86
Revises: 62cdf51dca49
Create Date: 2026-05-25 20:44:49.248250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b46762debd86'
down_revision: Union[str, None] = '62cdf51dca49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_exchange_rates_currency_date'), 'exchange_rates', type_='unique')
    op.create_index('uq_exchange_rates_currency_date', 'exchange_rates', ['currency_code', 'effective_date'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_exchange_rates_currency_date', table_name='exchange_rates', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_exchange_rates_currency_date'), 'exchange_rates', ['currency_code', 'effective_date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
