"""initial schema

Revision ID: db0d114b5777
Revises: 
Create Date: 2026-05-23 08:48:43.750269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'db0d114b5777'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=5), nullable=False),
    sa.Column('decimal_places', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], name='fk_product_categories_parent_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parent_id', name='uq_product_categories_name_parent')
    )
    op.create_index('ix_product_categories_parent_id', 'product_categories', ['parent_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('role', sa.Enum('admin', 'operator', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_warehouses_one_default', 'warehouses', ['is_default'], unique=True, postgresql_where=sa.text('is_default = true AND deleted_at IS NULL'))
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'restore', 'confirm', 'cancel', name='audit_action'), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_audit_log_user_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_log_user_id', 'audit_log', ['user_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_type', sa.Enum('customer', 'supplier', 'both', name='contact_type'), nullable=False),
    sa.Column('document_type', sa.Enum('ruc', 'ci', 'passport', 'none', name='document_type'), nullable=False),
    sa.Column('document_number', sa.String(length=30), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('trade_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_contacts_created_by_user_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name='fk_contacts_updated_by_user_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_business_name', 'contacts', ['business_name'], unique=False)
    op.create_index('ix_contacts_contact_type', 'contacts', ['contact_type'], unique=False)
    op.create_index('ix_contacts_document_number', 'contacts', ['document_number'], unique=False, postgresql_where=sa.text('document_number IS NOT NULL'))
    op.create_table('exchange_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('rate_to_base', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_exchange_rates_created_by_user_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], name='fk_exchange_rates_currency_code', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_code', 'effective_date', name='uq_exchange_rates_currency_date')
    )
    op.create_index('ix_exchange_rates_lookup', 'exchange_rates', ['currency_code', 'effective_date'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('base_unit', sa.String(length=20), nullable=False),
    sa.Column('track_stock', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='10.00', nullable=False),
    sa.Column('tax_included_in_price', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100', name='ck_products_tax_rate_range'),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name='fk_products_category_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_products_created_by_user_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name='fk_products_updated_by_user_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', name='uq_products_sku')
    )
    op.create_index('ix_products_barcode', 'products', ['barcode'], unique=False, postgresql_where=sa.text('barcode IS NOT NULL'))
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.create_index('ix_products_is_active', 'products', ['is_active'], unique=False)
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.Enum('string', 'int', 'decimal', 'bool', 'json', name='setting_value_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name='fk_settings_updated_by_user_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('stock_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('adjustment_number', sa.String(length=30), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('adjustment_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Enum('inventory_count', 'damage', 'loss', 'expired', 'correction', 'other', name='adjustment_reason'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'confirmed', 'cancelled', name='adjustment_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_stock_adjustments_created_by_user_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name='fk_stock_adjustments_updated_by_user_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='fk_stock_adjustments_warehouse_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adjustment_number', name='uq_stock_adjustments_adjustment_number')
    )
    op.create_table('product_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('unit_name', sa.String(length=30), nullable=False),
    sa.Column('factor_to_base', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_default_sale_unit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_default_purchase_unit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('factor_to_base > 0', name='ck_product_units_factor_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_product_units_product_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'unit_name', name='uq_product_units_product_unit_name')
    )
    op.create_index('ix_product_units_barcode', 'product_units', ['barcode'], unique=False, postgresql_where=sa.text('barcode IS NOT NULL'))
    op.create_index('ix_product_units_product_id', 'product_units', ['product_id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('supplier_document_number', sa.String(length=30), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('total_base_currency', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('draft', 'confirmed', 'cancelled', name='purchase_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_purchases_created_by_user_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], name='fk_purchases_currency_code', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['contacts.id'], name='fk_purchases_supplier_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name='fk_purchases_updated_by_user_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='fk_purchases_warehouse_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_number', name='uq_purchases_purchase_number')
    )
    op.create_index('ix_purchases_purchase_date', 'purchases', ['purchase_date'], unique=False)
    op.create_index('ix_purchases_status', 'purchases', ['status'], unique=False)
    op.create_index('ix_purchases_supplier_id', 'purchases', ['supplier_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_number', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('sale_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('items_subtotal', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('items_discount_total', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('header_discount_amount', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('header_discount_type', sa.Enum('amount', 'percent', name='discount_type'), nullable=False),
    sa.Column('header_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('total_base_currency', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('cost_total_base', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('draft', 'confirmed', 'cancelled', name='sale_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_sales_created_by_user_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], name='fk_sales_currency_code', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['contacts.id'], name='fk_sales_customer_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name='fk_sales_updated_by_user_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='fk_sales_warehouse_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_number', name='uq_sales_sale_number')
    )
    op.create_index('ix_sales_customer_id', 'sales', ['customer_id'], unique=False)
    op.create_index('ix_sales_sale_date', 'sales', ['sale_date'], unique=False)
    op.create_index('ix_sales_status', 'sales', ['status'], unique=False)
    op.create_index('ix_sales_warehouse_id', 'sales', ['warehouse_id'], unique=False)
    op.create_table('stock_current',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('quantity_base', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('avg_cost_base', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('last_movement_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_stock_current_product_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='fk_stock_current_warehouse_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_id', 'warehouse_id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('purchase', 'sale', 'return_in', 'return_out', 'adjustment_in', 'adjustment_out', 'initial', name='stock_movement_type'), nullable=False),
    sa.Column('direction', sa.Enum('in', 'out', name='stock_direction'), nullable=False),
    sa.Column('quantity_base', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost_base', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('reference_type', sa.Enum('purchase', 'sale', 'adjustment', name='stock_reference_type'), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("direction = 'out' OR unit_cost_base IS NOT NULL", name='ck_stock_movements_cost_required_on_in'),
    sa.CheckConstraint('quantity_base > 0', name='ck_stock_movements_quantity_positive'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_stock_movements_created_by_user_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_stock_movements_product_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='fk_stock_movements_warehouse_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_movements_created_at', 'stock_movements', ['created_at'], unique=False)
    op.create_index('ix_stock_movements_product_warehouse', 'stock_movements', ['product_id', 'warehouse_id', 'created_at'], unique=False)
    op.create_index('ix_stock_movements_reference', 'stock_movements', ['reference_type', 'reference_id'], unique=False)
    op.create_table('product_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_unit_id', sa.UUID(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('price >= 0', name='ck_product_prices_non_negative'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_product_prices_created_by_user_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], name='fk_product_prices_currency_code', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_unit_id'], ['product_units.id'], name='fk_product_prices_product_unit_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_unit_id', 'currency_code', 'effective_from', name='uq_product_prices_unit_currency_date')
    )
    op.create_index('ix_product_prices_lookup', 'product_prices', ['product_unit_id', 'currency_code', 'effective_from'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_unit_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_base', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost_base_currency', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('tax_included', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_number', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_purchase_items_quantity_positive'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_purchase_items_cost_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_purchase_items_product_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_unit_id'], ['product_units.id'], name='fk_purchase_items_product_unit_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name='fk_purchase_items_purchase_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchase_items_product_id', 'purchase_items', ['product_id'], unique=False)
    op.create_index('ix_purchase_items_purchase_id', 'purchase_items', ['purchase_id'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_unit_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_base', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('discount_type', sa.Enum('amount', 'percent', name='discount_type'), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('tax_included', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost_base_at_sale', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_number', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_sale_items_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_sale_items_price_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_sale_items_product_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_unit_id'], ['product_units.id'], name='fk_sale_items_product_unit_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name='fk_sale_items_sale_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_items_product_id', 'sale_items', ['product_id'], unique=False)
    op.create_index('ix_sale_items_sale_id', 'sale_items', ['sale_id'], unique=False)
    op.create_table('sale_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'transfer', 'card_debit', 'card_credit', 'check', 'other', name='payment_method'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_sale_payments_amount_positive'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name='fk_sale_payments_sale_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_payments_sale_id', 'sale_payments', ['sale_id'], unique=False)
    op.create_table('stock_adjustment_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('adjustment_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_unit_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_base', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('direction', sa.Enum('in', 'out', name='stock_direction'), nullable=False),
    sa.Column('unit_cost_base', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['adjustment_id'], ['stock_adjustments.id'], name='fk_stock_adjustment_items_adjustment_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_stock_adjustment_items_product_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_unit_id'], ['product_units.id'], name='fk_stock_adjustment_items_product_unit_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_adjustment_items')
    op.drop_index('ix_sale_payments_sale_id', table_name='sale_payments')
    op.drop_table('sale_payments')
    op.drop_index('ix_sale_items_sale_id', table_name='sale_items')
    op.drop_index('ix_sale_items_product_id', table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index('ix_purchase_items_purchase_id', table_name='purchase_items')
    op.drop_index('ix_purchase_items_product_id', table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index('ix_product_prices_lookup', table_name='product_prices')
    op.drop_table('product_prices')
    op.drop_index('ix_stock_movements_reference', table_name='stock_movements')
    op.drop_index('ix_stock_movements_product_warehouse', table_name='stock_movements')
    op.drop_index('ix_stock_movements_created_at', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_table('stock_current')
    op.drop_index('ix_sales_warehouse_id', table_name='sales')
    op.drop_index('ix_sales_status', table_name='sales')
    op.drop_index('ix_sales_sale_date', table_name='sales')
    op.drop_index('ix_sales_customer_id', table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_purchases_supplier_id', table_name='purchases')
    op.drop_index('ix_purchases_status', table_name='purchases')
    op.drop_index('ix_purchases_purchase_date', table_name='purchases')
    op.drop_table('purchases')
    op.drop_index('ix_product_units_product_id', table_name='product_units')
    op.drop_index('ix_product_units_barcode', table_name='product_units', postgresql_where=sa.text('barcode IS NOT NULL'))
    op.drop_table('product_units')
    op.drop_table('stock_adjustments')
    op.drop_table('settings')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_index('ix_products_is_active', table_name='products')
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_index('ix_products_barcode', table_name='products', postgresql_where=sa.text('barcode IS NOT NULL'))
    op.drop_table('products')
    op.drop_index('ix_exchange_rates_lookup', table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_index('ix_contacts_document_number', table_name='contacts', postgresql_where=sa.text('document_number IS NOT NULL'))
    op.drop_index('ix_contacts_contact_type', table_name='contacts')
    op.drop_index('ix_contacts_business_name', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_audit_log_user_id', table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index('ix_audit_log_created_at', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('uq_warehouses_one_default', table_name='warehouses', postgresql_where=sa.text('is_default = true AND deleted_at IS NULL'))
    op.drop_table('warehouses')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_product_categories_parent_id', table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_table('currencies')
    # Drop PostgreSQL enum types (not generated by autogenerate)
    sa.Enum(name='payment_method').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='discount_type').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='sale_status').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='purchase_status').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='adjustment_status').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='adjustment_reason').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='stock_reference_type').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='stock_direction').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='stock_movement_type').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='document_type').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='contact_type').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='audit_action').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='setting_value_type').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
